/*
  # Add More Recommendations and Games

  1. Additional Recommendations
    - 20+ new personalized recommendations across all categories
    - Comprehensive mental health guidance
  
  2. Additional Psychology Games
    - 6 new interactive exercises
    - Expanded difficulty levels
    - Various therapeutic techniques
*/

-- Add more recommendations
INSERT INTO recommendations (category, title, description, content, icon) VALUES
  ('ansiedad', 'Técnica de Relajación Muscular Progresiva', 'Reduce ansiedad física y mental', 'Siéntate en un lugar cómodo. Comienza con los dedos de los pies: tensa todos los músculos durante 5 segundos, luego relaja completamente. Siente la diferencia. Continúa con cada parte del cuerpo (pantorrillas, muslos, abdomen, pecho, brazos, cuello, cara). Esta técnica es excelente para liberar la tensión acumulada.', 'wind'),
  ('ansiedad', 'Desafía tus Preocupaciones', 'Cuestiona el ciclo de la preocupación', 'Cuando te sientas ansioso, escribe tus preocupaciones. Luego pregúntate: ¿Es probable que suceda? ¿Qué tan malo sería realmente? ¿Podría manejar esa situación? A menudo descubriremos que nuestras preocupaciones son exageradas.', 'message-circle'),
  ('ansiedad', 'Mantén una Rutina Diaria', 'La consistencia reduce la ansiedad', 'El cerebro encuentra seguridad en la rutina. Establece horarios para despertar, comer, trabajar, ejercicio y dormir. Mantén estos horarios consistentemente. Esto reduce la incertidumbre y disminuye significativamente los niveles de ansiedad.', 'coffee'),
  ('estres', 'Técnica del Tiempo de Preocupación', 'Controla tu estrés mentalmente', 'Designa 15-30 minutos específicos del día como "tiempo de preocupación". Si una preocupación surge fuera de este tiempo, escríbela y déjala para luego. Durante el tiempo designado, permite que tu mente se preocupe plenamente. Esto paradójicamente reduce la preocupación general.', 'clock'),
  ('estres', 'Practica la Dicción de No', 'Establece límites saludables', 'Decir "no" es un acto de autocuidado, no de egoísmo. Practica respuestas claras: "No puedo en este momento", "Necesito tiempo para pensarlo", "Eso no funciona para mí". Los límites saludables reducen dramáticamente el estrés.', 'shield'),
  ('estres', 'Método de Resolución de Problemas', 'Aborda el estrés constructivamente', 'Define el problema claramente. Genera múltiples soluciones posibles. Evalúa pros y contras de cada una. Elige la mejor opción. Implementa y evalúa. Resolver problemas activamente reduce la ansiedad más que preocuparse pasivamente.', 'brain'),
  ('autoestima', 'Práctica de Afirmaciones Positivas', 'Reprograma tu diálogo interno', 'Cada mañana, repite afirmaciones positivas específicas: "Soy capaz", "Merezco amor y respeto", "Tengo habilidades valiosas". Repítelas 5 veces cada una. Tu cerebro eventualmente comenzará a creer lo que repites constantemente.', 'heart'),
  ('autoestima', 'Reconoce tus Fortalezas', 'Enfócate en lo que haces bien', 'Haz una lista de 10 cosas en las que eres bueno. Pueden ser grandes o pequeñas. Revísala regularmente, especialmente cuando sientas que tu autoestima está baja. Recordar tus fortalezas contrarresta el pensamiento negativo automático.', 'sparkles'),
  ('autoestima', 'Cultiva la Autofarmacología', 'Sé amable contigo mismo', 'Trata tus errores como lo harías con un amigo querido: con compasión. Reconoce que cometer errores es humano. No te castigues emocionalmente. La autocompasión es más efectiva que la autocrítica para el crecimiento personal.', 'heart-handshake'),
  ('autoestima', 'Rodéate de Personas Positivas', 'El ambiente influye tu autoestima', 'Pasa tiempo con personas que te apoyan, te animan y celebran tus logros. Minimiza el tiempo con críticos constantes. Las personas en tu círculo influyen enormemente en cómo te ves a ti mismo.', 'users'),
  ('bienestar', 'Hidratación Consciente', 'El agua es medicina', 'Bebe al menos 8 vasos de agua al día. La deshidratación afecta directamente tu estado de ánimo y energía. Haz de beber agua una práctica consciente: siente el agua, aprecia la frescura. Mantente hidratado para un mejor bienestar mental.', 'droplet'),
  ('bienestar', 'Nutrición y Ánimo', 'Cuidar tu dieta, cuidar tu mente', 'Aumenta alimentos ricos en omega-3 (pescado, nueces), vitamina D (huevos, queso), magnesio (verduras de hoja verde). Reduce azúcares refinados y alimentos ultraprocesados. La nutrición es fundamental para la salud mental.', 'apple'),
  ('bienestar', 'Exposición al Sol', 'La luz es terapia natural', 'Pasa al menos 30 minutos al día bajo la luz natural del sol. La exposición solar regula tu ritmo circadiano, aumenta vitamina D y libera serotonina. Sin forzar: camina al aire libre, siéntate en una ventana, disfruta de la naturaleza.', 'sun'),
  ('bienestar', 'Crea un Espacio Seguro', 'Tu entorno impacta tu bienestar', 'Dedica un espacio en tu hogar donde te sientas completamente seguro y relajado. Puede ser una esquina con almohadas, una habitación, o un rincón. Personalízalo con colores calmantes, plantas, música suave. Visita este espacio cuando necesites recargar.', 'home'),
  ('mindfulness', 'Práctica del Aquí y Ahora', 'Vive en el presente', 'Cuando tu mente divague al pasado o futuro, gentilmente trae tu atención al presente. ¿Qué ves? ¿Qué escuchas? ¿Qué sientes? El presente es el único momento en el que realmente vives. Practica esto varias veces al día.', 'eye'),
  ('mindfulness', 'Caminata Consciente', 'Transforma tu ejercicio en meditación', 'Durante tu caminata, nota cada paso. Siente el contacto de tus pies con el suelo. Observa tu respiración. Mira a tu alrededor con curiosidad. No es sobre llegar a un destino, es sobre estar presente en el viaje.', 'activity'),
  ('mindfulness', 'Comer Conscientemente', 'Transforma tu relación con la comida', 'Come despacio. Mastica completamente cada bocado (al menos 20 veces). Nota los sabores, texturas, aromas. Aprecia el alimento. Comer conscientemente puede transformar tu relación con la comida y mejorar la digestión.', 'utensils'),
  ('mindfulness', 'Sonidos Conscientes', 'Escucha profundamente', 'Siéntate en silencio durante 5 minutos. Escucha todos los sonidos a tu alrededor. No juzgues, solo observa. Hay belleza en sonidos que normalmente ignoramos. Esta práctica cultiva la atención plena y la apreciación.', 'headphones'),
  ('autoestima', 'Acepta tus Imperfecciones', 'La perfección no existe', 'Eres imperfecto, y eso es perfecto. Las imperfecciones son lo que te hace humano e interesante. En lugar de esconderlas, acéptalas como parte de tu historia. Esto libera enorme energía que gastabas en ser perfecto.', 'sparkles'),
  ('estres', 'Pausa Digital', 'Desconéctate para reconectarte', 'Designa horas sin pantallas, especialmente antes de dormir. Las redes sociales y notificaciones constantes generan estrés. Dedica este tiempo a actividades que relajan: lectura, arte, naturaleza. Tu sistema nervioso se regenerará.', 'smartphone');

-- Add more psychology games
INSERT INTO psychology_games (name, description, category, instructions, difficulty) VALUES
  ('Cuerpo de Exploración', 'Descubre la conexión mente-cuerpo', 'meditation', 'Acuéstate cómodamente. Comienza en los dedos de los pies. Lentamente examina cada parte de tu cuerpo buscando sensaciones. ¿Hay tensión? ¿Dolor? ¿Relajación? Sin tratar de cambiar nada, solo observa con curiosidad neutral. Continúa hacia la cabeza.', 'medium'),
  ('Rueda de Emociones', 'Identifica y valida tus emociones', 'cognitive', 'Se presenta una emoción. Tu tarea es identificar la raíz probable (necesidad insatisfecha). Luego elige una respuesta saludable. ¿Es una emoción común? ¿Cómo puede guiarte? Las emociones son mensajeros, no enemigos.', 'medium'),
  ('Cinco Sentidos', 'Practica la conexión sensorial', 'mindfulness', 'En tu entorno actual, identifica: 5 cosas que puedas VER, 4 que puedas TOCAR, 3 que puedas OÍR, 2 que puedas OLER, 1 que puedas SABOREAR. Este ejercicio te ancla al presente inmediato y reduce la ansiedad.', 'easy'),
  ('Autoaprecio', 'Cultiva la autocompasión', 'mindfulness', 'Cierra los ojos. Visualiza a alguien que amas incondicionalmente. Ahora visualízate a ti mismo con ese mismo amor. Repite lentamente: "Soy digno de amor", "Merezco amabilidad", "Estoy haciendo mi mejor esfuerzo". Siente estas palabras en tu cuerpo.', 'easy'),
  ('Rememoración Positiva', 'Accede a tus recursos internos', 'meditation', 'Recuerda un momento donde te sentiste completamente seguro, amado y en paz. Recrea todos los detalles sensoriales. ¿Qué veías? ¿Cómo olía? ¿Qué sonidos había? Cuando necesites paz, vuelve a este recuerdo.', 'easy'),
  ('Debate de Pensamientos', 'Desafía creencias limitantes', 'cognitive', 'Se presenta una creencia limitante común ("No soy lo suficientemente bueno", "Siempre fracaso"). Tu tarea es generar una evidencia en contra convincente de tu propia vida. Cuestiona la validez de la creencia.', 'hard'),
  ('Técnica Somática', 'Libera tensión del cuerpo', 'breathing', 'De pie con los pies separados. Lentamente sube los hombros a los oídos, tensa por 5 segundos, luego deja caer bruscamente. Repite 5 veces. Luego sacude ligeramente los brazos y las piernas. Esto despierta el sistema nervioso dormido.', 'easy'),
  ('Conversación Interna', 'Transforma tu diálogo interno', 'cognitive', 'Se presenta un diálogo interno negativo (crítica, auto-sabotaje). Tu tarea es transformarlo en algo más compasivo y realista. ¿Cómo un mentor amoroso te hablaría en esta situación?', 'medium');
